Traceback (most recent call last):
  File "/opt/miniconda3/envs/echem/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/miniconda3/envs/echem/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/miniconda3/envs/echem/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/miniconda3/envs/echem/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/miniconda3/envs/echem/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/miniconda3/envs/echem/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/miniconda3/envs/echem/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/miniconda3/envs/echem/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
coord = [[0.0, 0.0, 0.0]]

two_part_den_aa = vis_drv.get_two_particle_density(coord, coord, molecule, basis,
                                               density, 'alpha', 'alpha')
two_part_den_ab = vis_drv.get_two_particle_density(coord, coord, molecule, basis,
                                               density, 'alpha', 'beta')

print(f'Two-particle density     (same spin): {two_part_den_aa[0]:10.4f} a.u.')
print(f'Two-particle density (opposite spin): {two_part_den_ab[0]:10.4f} a.u.')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[7], line 4[0m
[1;32m      1[0m coord [38;5;241m=[39m [[[38;5;241m0.0[39m, [38;5;241m0.0[39m, [38;5;241m0.0[39m]]
[1;32m      3[0m two_part_den_aa [38;5;241m=[39m vis_drv[38;5;241m.[39mget_two_particle_density(coord, coord, molecule, basis,
[0;32m----> 4[0m                                                [43mdensity[49m, [38;5;124m'[39m[38;5;124malpha[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124malpha[39m[38;5;124m'[39m)
[1;32m      5[0m two_part_den_ab [38;5;241m=[39m vis_drv[38;5;241m.[39mget_two_particle_density(coord, coord, molecule, basis,
[1;32m      6[0m                                                density, [38;5;124m'[39m[38;5;124malpha[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mbeta[39m[38;5;124m'[39m)
[1;32m      8[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m'[39m[38;5;124mTwo-particle density     (same spin): [39m[38;5;132;01m{[39;00mtwo_part_den_aa[[38;5;241m0[39m][38;5;132;01m:[39;00m[38;5;124m10.4f[39m[38;5;132;01m}[39;00m[38;5;124m a.u.[39m[38;5;124m'[39m)

[0;31mNameError[0m: name 'density' is not defined
NameError: name 'density' is not defined

